version: '9'
services:
 db:
    image: mysql:latest
    container_name: snakeGameDB
    ports:
     - "3306:3306"
    environment:
      MYSQL_DATABASE: 'snake_game'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
        - my-db:/var/lib/mysql
volumes:
  my-db: